Feat/93/ StatisticRecord Create feature
project-studying-dotnet/Streetcode-Server-December pull request #121
Opened 2024-12-17 15:14 UTC by AndriiTans

## Board

[Link to ticket](https://github.com/project-studying-dotnet/Streetcode-Server-December/issues/93)

2024-12-17 20:48 UTC, oliatu approved these changes

2024-12-17 22:33 UTC, max-khakimzhanov requested changes

2024-12-18 06:57 UTC, AndriiTans commented on Streetcode/Streetcode.BLL/MediatR/Analytics/Create/CreateStatisticRecordHandler.cs
> +        }
Removed

2024-12-18 08:53 UTC, max-khakimzhanov approved these changes

2024-12-18 08:54 UTC, merged