Test/120/add fluent validation and write tests
project-studying-dotnet/Streetcode-Server-December pull request #191
Opened 2024-12-22 17:05 UTC by Gorgggulia

TimelineItemCreateDTO
CreateTimelineItemCommand

FactCreateDTO
CreateFactCommand

Covered validators with tests

CHECK LIST

 СI passed
 Сode coverage >=95%
 PR is reviewed manually again (to make sure you have 100% ready code)
 All reviewers agreed to merge the PR
 I've checked new feature as logged in and logged out user if needed
 PR meets all conventions

2024-12-23 07:09 UTC, BlackkTurtle approved these changes

2024-12-26 19:24 UTC, max-khakimzhanov requested changes
1. What is project.zip file for?
2. Fix build errors

2024-12-27 15:40 UTC, synapsetron requested changes

2024-12-27 15:40 UTC, synapsetron commented on Streetcode/Streetcode.BLL/DTO/Timeline/Create/TImelineItemCreateDto.cs
> +        public TeamMemberDTO TeamMember { get; set; }
Звідки це поле? Його немає в TimelineItem Entity

2024-12-27 20:37 UTC, max-khakimzhanov requested changes
Sonar shows that 2 tests failed

2024-12-27 20:37 UTC, max-khakimzhanov commented on Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Create/CreateTimelineItemCommand.cs
> +     public TimelineItemCreateDto TimelineItem { get; set; }
Why did you add this property?
The primary constructor of records type implies that this property is created automatically

2024-12-27 20:37 UTC, max-khakimzhanov commented on Streetcode/Streetcode.BLL/MediatR/Streetcode/Fact/Create/CreateFactCommand.cs
> +using Streetcode.BLL.DTO.Media.Art;
This using directive is not necessary

2024-12-27 20:37 UTC, max-khakimzhanov commented on Streetcode/Streetcode.BLL/DTO/Timeline/Create/TImelineItemCreateDto.cs
> +        public TeamMemberDTO TeamMember { get; set; }
In the task is not required to change this Dto

2024-12-31 07:28 UTC, vladtymo commented
Too many unnecessary changes. Refactor, clean up the code and create new PR

2024-12-31 07:28 UTC, closed without merging