feat/206: Add CookieMiddleware to store JWT tokens in cookies
project-studying-dotnet/Streetcode-Server-December pull request #231
Opened 2024-12-26 19:14 UTC by max-khakimzhanov

- Add CookieMiddleware to store JWT tokens in cookies
- Cover with tests

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-12-27 07:18 UTC, oliatu approved these changes

2024-12-28 11:21 UTC, synapsetron approved these changes

2024-12-28 19:53 UTC, BlackkTurtle approved these changes

2024-12-28 20:20 UTC, BlackkTurtle requested changes
Look why SonarCloud Quality gate does not pass

2024-12-30 10:02 UTC, closed without merging